### ISSUE TITLE
Please support spaces in publisher name

### ISSUE THREAD

**Issue by tikr7** [pluralsh/plural-cli#22]
plural cli version: Compiled At: 2022-03-04

## How to reproduce?
```
plural create
? Enter the name of your application:  kyverno-dask
? Enter the name of your publisher: Alexander Thamm
...
```
## Fix

`Pluralfile` has the publisher name without quotes`Alexander Thamm` but it needs to be `"Alexander Thamm"`

## Error
Otherwise the following error will occur:
```
plural apply -f kyverno-dask/Pluralfile
2022/03/04 11:07:06 open .../kyverno-dask/Thamm: no such file or directory
```

**Comment by michaeljguarino** [comment]
Ah yeah the plural create command doesn't quote by default, will work on a fix to this asap

**Comment by michaeljguarino** [comment]
The fix for this is actually in the plural repo here: https://github.com/pluralsh/plural/commit/013bb1bb46793ba8e67de30926c9f21ac02e7587.  It should deploy in a few minutes and the `plural create` command ought to behave as expected after.

**Comment by tikr7** [comment]
Thank you, @michaeljguarino 
Today I tested it and I can confirm it is fixed =)
