### ISSUE TITLE
Validate bucket names are workspace unique

### ISSUE THREAD

**Issue by michaeljguarino** [pluralsh/plural-cli#32]
## Use Case
It's techically possible for users to provide the same bucket name twice in an installation.  This will cause issues in terraform double-creating buckets and failing deployments.  We should figure out a way to ensure uniqueness of buckets across a workspace.

## Ideas of Implementation
* not sure of a good solve here, we can keep them in a set during recipe install, although that'll miss on separate recipes.  Could also just theoretically see if it collides with the value of some element of the context.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by jpcassil** [comment]
Both (current) prompts for airbyte look very similar and I think it could also help if it was a little more clear that it's not a glitch (it did accept the first value, but it actually needs another bucket name for a different bucket.)

```
wal_bucket
? Enter a globally unique bucket name, will be formatted as 6rs-test-airbyte-<your-input> arbitrary
airbyte unified data integration platform

airbyteBucket
? Enter a globally unique bucket name, will be formatted as 6rs-test-airbyte-<your-input> arbitrary2

```

It just so happened that in my terminal `wal_bucket` and `airbyteBucket` were obscured. so I think it might work a bit better with a prompt like this?:

```
? Enter a globally unique bucket name for the airbyteBucket, which will be formatted as 6rs-test-airbyte-<your-input> arbitrary2
```

**Comment by michaeljguarino** [comment]
This should now be addressed, although we'll also work with some of the messaging issues there too
