### ISSUE TITLE
`plural init` hangs when subsequently creating an account on plural.sh

### ISSUE THREAD

**Issue by fabricetriboix** [pluralsh/plural-cli#43]
## Summary
Running `plural init` hangs if the user does not have an account on plural.sh already and creates an account on-the-fly.

## Reproduction
Run `plural init` and try to create a new account on plural.sh when the browser window shows up

## Additional Info about Your Environment
Ubuntu 21.10

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by michaeljguarino** [comment]
Closing this in favor of https://github.com/pluralsh/plural/issues/215
