### ISSUE TITLE
More sanitized error message when subdomain is already registered

### ISSUE THREAD

**Issue by samweaver** [pluralsh/plural-cli#49]
![image](https://user-images.githubusercontent.com/91291764/165138706-8acde91b-b0bb-469b-a9cc-4f746c25552e.png)

Suggested error message: Subdomain is already taken.

**Comment by KiranSatyaRaj** [comment]
Hey @samweaver, I can do this, I need some help with navigating to that file.

**Comment by floreks** [comment]
Sorry for the confusion but it seems that this issue has been fixed: https://github.com/pluralsh/plural-cli/blob/e1f2779850fdad785b013e75efd64b3e9de38424/pkg/manifest/manifest.go#L151-L156
