### ISSUE TITLE
Sort entries in output.tf

### ISSUE THREAD

**Issue by DavidSpek** [pluralsh/plural-cli#90]
## Use Case
The `output.tf` file that is created during `plural build` is not sorted. This often causes the order of the outputs to be changed with subsequent `plural build` commands, causing the terraform to be deployed unnecessarily.

## Ideas of Implementation
Sort the output entries in the `output.tf` file so that unnecessary terraform build and deploys don't occur.

**Comment by DavidSpek** [comment]
@michaeljguarino

**Comment by michaeljguarino** [comment]
I thought we did sort these

**Comment by DavidSpek** [comment]
I'll confirm again then, but I did see terraform deploy a couple times without actual changes because of something like this.
